config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :categories
  resources :accounts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'dashboard#index'

  root 'dashboard#index'
end

app/models/category.rb
class Category < ApplicationRecord

  validates :name, presence: true, length: {minimum: 5}
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_url, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_url, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  OptionsForCategory = Struct.new(:id, :description)

  def options_for_categories
    Category.all.order(:name).map { |cat| OptionsForCategory.new(cat.id, cat.name)}
  end
end

app/views/categories/_form.html.erb
<h1 class="page-header"><%= Category.model_name.human() %></h1>
<% if @category.errors.any? %>
<div class="alert alert-danger alert-dismissable">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
  <ul>
    <% @category.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="panel panel-default">
<div class="panel-heading"><%= action %></div>
<!-- /.panel-heading -->

<div class="panel-body">
  <%= form_for @category do |f| %>
  <div class="form-group">
    <label><%= Category.human_attribute_name("name") %></label>
    <%= f.text_field :name, class: "form-control", placeholder: "Enter text" %>
  </div>

  <%= submit_tag t('labels.save'), {class: "btn btn-primary"} %>
  <%= link_to t('labels.back'), categories_path, {class: 'btn btn-outline btn-danger'} %>
<% end %>
</div>
<!-- /.panel-body -->
</div>

app/views/categories/edit.html.erb
<%= render partial: 'form', locals: {action: t('labels.edit')} %>

app/views/categories/index.html.erb
<h1 class="page-header"><%= Category.model_name.human(count: 2) %></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to new_category_path, class:'btn btn-success btn-circle pull-right' do %>
    <i class="fa fa-plus"></i>
  <% end %>
  <%= t('labels.listing') %>
</div>
<!-- /.panel-heading -->

<div class="panel-body">
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th> # </th>
          <th><%= Category.human_attribute_name("name") %></th>
          <th ></th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td>
              <%= link_to edit_category_path(category), class: "btn btn-info btn-circle" do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to category_path(category), method: :delete, data: {confirm: t('messages.confirm_destroy_with', item: category.name)}, class: "btn btn-danger btn-circle" do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<!-- /.table-responsive -->
</div>
<!-- /.panel-body -->
</div>

app/views/categories/new.html.erb
<%= render partial: 'form', locals: {action: t('labels.new')} %>