config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :categories
  resources :accounts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'dashboard#index'

  root 'dashboard#index'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    conditions = " 1 = 1 "
    if !params['transaction'].nil?
      if !params['transaction']['initial_date'].nil? && !params['transaction']['initial_date'].empty?
        conditions += " AND date >= '#{Date.parse(params['transaction']['initial_date']).strftime('%Y-%m-%d')}' "
      end
      if !params['transaction']['final_date'].nil? && !params['transaction']['final_date'].empty?
        conditions += " AND date <= '#{Date.parse(params['transaction']['final_date']).strftime('%Y-%m-%d')}' "
      end

      if !params['transaction']['basis_initial_date'].nil? && !params['transaction']['basis_initial_date'].empty?
        conditions += " AND basis >= '#{Date.parse(params['transaction']['basis_initial_date']).strftime('%Y-%m-%d')}' "
      end
      if !params['transaction']['basis_final_date'].nil? && !params['transaction']['basis_final_date'].empty?
        conditions += " AND basis <= '#{Date.parse(params['transaction']['basis_final_date']).strftime('%Y-%m-%d')}' "
      end

    else
      conditions += " AND date >= '#{Date.today.beginning_of_month.strftime('%Y-%m-%d')}' "
      conditions += " AND date <= '#{Date.today.end_of_month.strftime('%Y-%m-%d')}' "
    end

    p conditions

    @transactions = Transaction.where(conditions).order(:date)
    @balance = @transactions.sum(:value)
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_url, notice: I18n.t('messages.created') }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_url, notice: I18n.t('messages.updated') }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:account_id, :category_id, :date, :basis, :title, :value, :done, :kind)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
  OptionsForTransactions = Struct.new(:id, :description)

  def options_for_kinds
    Transaction.kinds_i18n.map { |key, value| OptionsForTransactions.new(key, value) }
  end

end

app/views/transactions/_form.html.erb
<h1 class="page-header"><%= Transaction.model_name.human() %></h1>
<% if @transaction.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading"><%= action %></div>
  <!-- /.panel-heading -->

  <div class="panel-body">
    <%= form_for @transaction do |f| %>

      <div class="form-group">
        <label><%= Transaction.human_attribute_name("date") %></label>
        <%= f.date_field :date, class: "form-control" %>
      </div>

      <div class="form-group">
        <label><%= Transaction.human_attribute_name("basis") %></label>
        <%= f.date_field :basis, class: "form-control" %>
      </div>

      <div class="form-group">
        <label><%= Transaction.human_attribute_name("title") %></label>
        <%= f.text_field :title, class: "form-control", placeholder: "Enter text" %>
      </div>

      <div class="form-group">
        <label><%= Transaction.human_attribute_name("kind") %></label>
        <%= f.collection_radio_buttons(:kind, options_for_kinds, :id, :description) do |opt| %>
        <div class="radio">
          <label>
            <%= opt.label { opt.radio_button + opt.text } %>
          </label>
        </div>
        <% end %>
      </div>

      <div class="form-group">
        <label><%= Account.model_name.human %></label>
        <%= f.collection_radio_buttons(:account_id, options_for_accounts, :id, :description) do |opt| %>
        <div class="radio">
          <label>
            <%= opt.label { opt.radio_button + opt.text } %>
          </label>
        </div>
        <% end %>
      </div>

      <div class="form-group">
        <label><%= Category.model_name.human %></label>
        <%= f.collection_select(:category_id, options_for_categories, :id, :description, {:prompt => t('messages.select')}, {class: "form-control"}) do |opt| %>
        <div>
          <label>
            <%= opt.label { opt.radio_button + opt.text } %>
          </label>
        </div>
        <% end %>
      </div>

      <div class="form-group">
        <label><%= Transaction.human_attribute_name("value") %></label>
        <%= f.number_field :value, class: "form-control", step: :any %>
      </div>

      <div class="form-group">
        <label><%= Transaction.human_attribute_name("done") %></label>
        <%= f.check_box :done %>
      </div>
    <%= submit_tag t('labels.save'), {class: "btn btn-primary"} %>
    <%= link_to t('labels.back'), transactions_path, {class: 'btn btn-outline btn-danger'} %>
<% end %>
</div>
<!-- /.panel-body -->
</div>

app/views/transactions/edit.html.erb
<%= render partial: 'form', locals: {action: t('labels.edit')} %>

app/views/transactions/index.html.erb
<h1 class="page-header"><%= Transaction.model_name.human(count: 2) %></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to new_transaction_path, class:'btn btn-success btn-circle pull-right' do %>
    <i class="fa fa-plus"></i>
  <% end %>
  <%= t('labels.listing') %>
</div>
<!-- /.panel-heading -->

<div class="panel-body">
  <div class="table-responsive">

    <%= form_tag transactions_path, method: :get, class: "navbar-form navbar-left search-form" do %>
      <label><%= t('labels.initial_date') %></label>
      <%= date_field("transaction", "initial_date") %>
      <label><%= t('labels.final_date') %></label>
      <%= date_field("transaction", "final_date") %>
      <br/>
      <label><%= t('labels.basis_date') %></label>
      <%= date_field("transaction", "basis_initial_date") %>
      <label><%= t('labels.basis_date') %></label>
      <%= date_field("transaction", "basis_final_date") %>
      <br/>
      <label><%= t('labels.consolidado_XXX') %></label>
      <%= check_box("transaction", "consolidado") %>
      <br/>
      <%= submit_tag t('labels.filter'), {class: "btn btn-default"} %>
    <% end %>

    <table class="table table-striped table-hover">
      <thead>
        <tr class="thead-dark">
          <th class="text-center">#</th>
          <th class="text-center"><%= Transaction.human_attribute_name("basis") %></th>
          <th class="text-center"><%= Transaction.human_attribute_name("date") %></th>
          <th class="text-center"><%= Transaction.human_attribute_name("title") %></th>
          <th class="text-center"><%= Account.model_name.human %></th>
          <th class="text-center"><%= Category.model_name.human %></th>
          <th class="text-center"><%= Transaction.human_attribute_name("kind") %></th>
          <th class="text-center"><%= Transaction.human_attribute_name("value") %></th>
          <th class="text-center"><%= Transaction.human_attribute_name("done") %></th>
          <th ></th>
        </tr>
      </thead>

      <tbody>
        <% @transactions.each do |transaction| %>
          <tr class="<%= transaction.debit? ? 'danger' : 'success'%>">
            <td class="text-center"><%= transaction.id %></td>
            <td class="text-center"><%= l(transaction.basis) %></td>
            <td class="text-center"><%= l(transaction.date) %></td>
            <td class="text-left"><%= transaction.title %></td>
            <td class="text-left"><%= transaction.account.name %></td>
            <td class="text-left"><%= transaction.category.name %></td>
            <td class="text-left"><%= transaction.kind_i18n %></td>
            <td class="text-right"><%= number_to_currency(transaction.value) %></td>
            <td class="text-center"><%= t("#{transaction.done}") %></td>
            <td class="text-center">
              <%= link_to edit_transaction_path(transaction), class: "btn btn-info btn-circle" do %>
              <i class="fa fa-edit"></i>
            <% end %>
              <%= link_to transaction_path(transaction), method: :delete, data: {confirm: t('messages.confirm_destroy_with', item: transaction.title)}, class: "btn btn-danger btn-circle" do %>
                <i class="fa fa-minus"></i>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <td colspan="7">SALDO PERÍODO</td>
        <td class="text-right" ><%= number_to_currency(@balance) %></td>
        <td colspan="2"></td>
    </tfoot>
  </table>
</div>
<!-- /.table-responsive -->
</div>
<!-- /.panel-body -->
</div>

app/views/transactions/new.html.erb
<%= render partial: 'form', locals: {action: t('labels.new')} %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @transaction.account %>
</p>

<p>
  <strong>Category:</strong>
  <%= @transaction.category %>
</p>

<p>
  <strong>Date:</strong>
  <%= @transaction.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @transaction.title %>
</p>

<p>
  <strong>Value:</strong>
  <%= @transaction.value %>
</p>

<p>
  <strong>Done:</strong>
  <%= @transaction.done %>
</p>

<p>
  <strong>Kind:</strong>
  <%= @transaction.kind %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>