config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :categories
  resources :accounts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'dashboard', to: 'dashboard#index'

  root 'dashboard#index'
end

app/models/account.rb
class Account < ApplicationRecord

  validates :name, presence: true, length: {minimum: 5}
  validates :kind, presence: true

  enum kind: {current: 0, investment: 1}

  has_many :transactions

  # TODO: COLOCAR O NOME DO MÉTODO NO PADRÃO EM INGLÊS
  def calculates_balance
    self.transactions.sum(:value)
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_url, notice: I18n.t('messages.created') }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to accounts_url, notice: I18n.t('messages.updated') }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: I18n.t('messages.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :kind)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  OptionsForKinds = Struct.new(:id, :description)
  OptionsForAccounts = Struct.new(:id, :description)

  def options_for_kinds
    Account.kinds_i18n.map { |key, value| OptionsForKinds.new(key, value) }
  end

  def options_for_accounts
    Account.all.order(:name).map {|acc| OptionsForAccounts.new(acc.id, acc.name) }
  end

end

app/views/accounts/_form.html.erb
<h1 class="page-header"><%= Account.model_name.human() %></h1>
<% if @account.errors.any? %>
  <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading"><%= action %></div>
  <!-- /.panel-heading -->

  <div class="panel-body">
    <%= form_for @account do |f| %>
    <div class="form-group">
      <label><%= Account.human_attribute_name("name") %></label>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter text" %>
    </div>

    <div class="form-group">
      <label><%= Account.human_attribute_name("kind") %></label>
      <%= f.collection_radio_buttons(:kind, options_for_kinds, :id, :description) do |opt| %>
      <div class="radio">
        <label>
          <%= opt.label { opt.radio_button + opt.text } %>
        </label>
      </div>
    <% end %>
  </div>

  <%= submit_tag t('labels.save'), {class: "btn btn-primary"} %>
  <%= link_to t('labels.back'), accounts_path, {class: 'btn btn-outline btn-danger'} %>
<% end %>
</div>
<!-- /.panel-body -->
</div>

app/views/accounts/edit.html.erb
<%= render partial: 'form', locals: {action: t('labels.edit')} %>

app/views/accounts/index.html.erb
<h1 class="page-header"><%= Account.model_name.human(count: 2) %></h1>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= link_to new_account_path, class:'btn btn-success btn-circle pull-right' do %>
    <i class="fa fa-plus"></i>
  <% end %>
  <%= t('labels.listing') %>
</div>
<!-- /.panel-heading -->

<div class="panel-body">
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th> # </th>
          <th><%= Account.human_attribute_name("name") %></th>
          <th><%= Account.human_attribute_name("kind") %></th>
          <th><%= t('labels.balance') %></th>
          <th ></th>
        </tr>
      </thead>

      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td><%= account.id %></td>
            <td><%= account.name %></td>
            <td><%= account.kind_i18n %></td>
            <td class="text-right"><%= number_to_currency(account.calculates_balance) %></td>
            <td>
              <%= link_to edit_account_path(account), class: "btn btn-info btn-circle" do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to account_path(account), method: :delete, data: {confirm: t('messages.confirm_destroy_with', item: account.name)}, class: "btn btn-danger btn-circle" do %>
                    <i class="fa fa-minus"></i>
                  <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<!-- /.table-responsive -->
</div>
<!-- /.panel-body -->
</div>

app/views/accounts/new.html.erb
<%= render partial: 'form', locals: {action: t('labels.new')} %>